Improve VSCode ext (realtime validation, build/reload script), and improve code org
- Fix IDE extension build and packaging workflow
- Fix tao vscode ts code block syntax highlighting
- Add VSCode tasks and improve launch configuration
- Symlink ide-syntaxes from compiler to ide-extension for shared syntax definitions
- Restructure all generated files to use _gen-* pattern for easier search/match
- Stub out basic compiler validation tests
- Update TODOs

diff --git a/packages/ide-extension/Justfile b/packages/ide-extension/Justfile
--- a/packages/ide-extension/Justfile
+++ b/packages/ide-extension/Justfile
@@ -7,29 +7,30 @@ dev:
     cursor --extensionDevelopmentPath .
 
 run:
-    echo "TODO: This isn't working yet -- unsure why."
-    exit 1
     echo
     echo "\tBuild and package extension..."
-    bunx @vscode/vsce package --allow-missing-repository --out ../../.builds/tao-lang-vscode.vsix # > /dev/null
+    bunx @vscode/vsce package --allow-missing-repository --out ../../.builds 2>&1 > /dev/null
     echo "\tInstall extension..."
-    just uninstall > /dev/null 2>&1 || true
+    just uninstall-extension > /dev/null 2>&1 || true
     just install-extension > /dev/null 2>&1
     echo "\tCheck extension installation..."
-    set -e && cursor --list-extensions | grep "tao.vscode-extension" > /dev/null || { echo "Installation failed -- extension not found" >&2; exit 1; }
-    echo "\n\t* Extension installed and loaded *\n"
+    set -e && cursor --list-extensions | grep "tao.tao-lang-vscode-extension" || { echo "Installation failed -- extension not found" >&2; exit 1; }
+    echo "\n\t* Extension installed - restart IDE *\n"
+    just restart-cursor
 
 uninstall-extension:
-    cursor --uninstall-extension tao.vscode-extension
+    cursor --uninstall-extension tao.tao-lang-vscode-extension
+
 install-extension:
-    cursor --install-extension ../../.builds/tao-lang-vscode.vsix --verbose
-    cursor --reload-window > /dev/null 2>&1
+    cursor --install-extension ../../.builds/tao-lang-vscode-extension-0.0.1.vsix --verbose --force
 
+restart-cursor:
+    osascript -e 'quit app "Cursor"'
+    sleep 0.25 && open -a Cursor && sleep 0.5 && open -a Cursor && sleep 0.5 && open -a Cursor
 
-build: _install
+[no-quiet]
+build: _install_deps
     cd ../compiler && just gen
-    mkdir -p ./gen-syntaxes/
-    cp ../compiler/gen-syntaxes/tao-lang.tmLanguage.json ./gen-syntaxes/tao-lang.tmLanguage.json
     tsc -b tsconfig.json
     node esbuild.mjs
 
@@ -38,9 +39,5 @@ watch:
         "tsc -b tsconfig.json --watch" \
         "node esbuild.mjs --watch"
 
-_install:
+_install_deps:
     bun install
-    # npm install
-
-clean:
-    rm -fr *.tsbuildinfo out gen-syntaxes
